# DAG Node Alerting Program
# v1.3b
# Author: hgtp://netmet
# ========================
#
# IMPORTANT:  See the README.md file in the github repo
#             or root of the DAG Node Alerting script
#             for more details and understanding of each
#             of the parameters in the configuration file
#             INCORRECT settings could leave to not only
#             unpredictable runtime issues, but it could
#             lead to inaccurate stats and information.
# 

configuration:
  notifications:
    node_username: root
    gmail_acct: gmail_source_email@gmail.com
    gmail_token: gmail_app_password
    email_recipients:
      enabled: false
      list:
        - whoever1@whoever.com      
        - whoever2@whoever.com
    mms_recipients:
      enabled: true
      add_subject: true
      list:
        - 111111111@provider.gateway.net
        - 222222222@provider.gateway.net
    node_name: My_Node
  constraints:
    error_max: 20
    memory_swap_min: 200000
    security_check: true
    uptime_threshold: 30
    load_threshold: .7
  healthcheck:
    enabled: false
    lb: put_the_constellation_lb_fully_qualified_domain_name_here
    lb_port: 9000
    node_ip: your_nodes_ext_ip_here
    node_port: 9001
    int_minutes: 5
    alarm_once: true
  intervals:
    time_zone: America/New_York
    start_time: '07:00'
    end_time: '20:00'
    int_minutes: 15
  splits:
    enabled: false
    split1: .7
    split2: .3
  collateral:
    enabled: false
    node_count: 1 
    free_dag: 0
  report:
    enabled: true
    estimates:
      - .10
      - .50
      - 1
      - 3
      - 5
      - 10
      - 50
